@startuml
' Classes abstraites
abstract class Collection {
  - items: dict
  + load(file_path)
  + save(file_path)
  + filter(criteria)
}

class CardCollection {
  - postcards: dict[str, Postcard]
  + load(file_path)
  + save(file_path)
  + filter_by_tags(tags)
  + filter_by_keywords(keywords)
  + filter_by_town(town)
  + filter_by_department(department)
  + filter_by_region(region)
}

abstract class Detection {
  - bbox: BoundingBox
  - is_manual: bool
  + process_content()
}

' Classes concrètes
class Postcard {
  - path: str
  - name: str
  - annotations: Annotations
  + get_annotations()
  + set_annotations(annotations: Annotations)
  + save_annotations()
  + load_annotations()
  + draw_bboxes()
  + rotate_image(angle)
  + plot() ?
  + to_array() ?
  + resize() ?
}

class Annotations {
  - location: Location
  - tags: list[str]
  - keywords: list[str]
  - detections: list[Detection]
  - rotation: int
'  + to_tensor()
'  + to_yolo_format()
'  + to_cvat_format()
  + set_location()
  + set_detections()
  + set_tags()
  + set_keywords()
}

class Location {
  - town: str
  - department: str
  - region: str
  - gps: tuple[float, float]
}

class BoundingBox {
  - x: float
  - y: float
  - w: float
  - h: float
  + rotate(angle)
  + transform(coords)
}

abstract class Text {
  - orientation: int
  - ocr_result: str
  - keywords: list[str]
  + process_content()
}

abstract class Postmark {
  - ...
  + process_content()
}

class Printed {
  - is_editor: bool
}

class Handwritten {
  - ...
}

class SceneText {
  - ...
}

class Stamp {
  - country: str
  - color: str
  - price: str
}

class DateStamp {
  - postal_agency: str
  - date: str
  - department: str
  - starred_hour: bool
  - collection: str
  - type
  - quality
}

class OtherMark {
  - type
}


' Relations
Collection <|.. CardCollection : hérite
CardCollection o--> "many" Postcard : contient
Postcard o--> "1" Annotations : contient
Annotations o--> "1" Location : contient
Location --> Printed : utilise
Annotations o--> "many" Detection : contient
Detection o--> "1" BoundingBox : contient
Detection <|.. Text : hérite
Detection <|.. Postmark : hérite
Text <|.. Printed : hérite
Text <|.. Handwritten : hérite
Text <|.. SceneText : hérite
Postmark <|.. Stamp : hérite
Postmark <|.. DateStamp : hérite
Postmark <|.. OtherMark : hérite
@enduml